// Initialize Supabase Client
const SUPABASE_URL = 'YOUR_SUPABASE_PROJECT_URL';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlZmdydHRscnVkbWZjcGdyZHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY2NTEwNTgsImV4cCI6MjEwMjIyNzA1OH0.u7X_hNhXMTw1R3dJOhA6BckKrQrscsbPknpWVVtxLqc';

const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
